# Generated by Django 6.0 on 2025-12-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(max_length=500, verbose_name='Ссылка на картинку'),
        ),
    ]
